### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by hwiguna**
Hi Brian!
First, thank you for all your work in making our lives easier. This CYD is easy to use because of your work.
I put together a clock with rolling digits that I'd like to share with other CYD owners.
I'm very unfamiliar with git so please let me know if there's a better procedure to follow.
https://youtu.be/y8mGTQBH4xI

### CODE REVIEW

**Comment by witnessmenow** [comment]
Love it Hari!

**Comment by danpeirce** [comment]
I really like this rolling clock project.
Very nice as is but it would be great if it could also display AM / PM too.

**Comment by yoezrasya** [comment]
Please file bin mophing clock i am not faile clock

**Comment by yoezrasya** [comment]
i am  clock not work that coding but done

**Comment by yoezrasya** [comment]
Please file bin morphing clock send emaol yoezrasya@hmail.com thank you very much

**Pull request merged**
