### PR TITLE
Functional touchscreen example in rust

### PR DESCRIPTION
**Pull request by bobsrac**
This targets a modified clone from Amazon:
https://www.amazon.com/dp/B0D4VCL6GR?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1

What was modified?
* Lifted XPT2046 sck, din, dout pins and tacked kynar wires over to GPIO22, 26 and 39.
mods

Why the mod?
* It worked as-shipped, but they reused the same SPI bus for the LCD and touch XPT2046.  The LCD can run at 80MHz, while he XPT2046 can run at 2.5MHz and that was severely limiting the screen update performance.

If you choose to convert/test this on a genuine CYD, I'd recommend making a few changes to start:
* ILI9486Rgb565 -> ILI9341 (lines 46, 244)
* maybe lower the clock from 80MHz down to 10-20MHz for initial testing
* back light pin 27 -> 21 (lines 119, 220)
* xpt2046 sck 22 -> 25
* xpt2046 mosi 26 -> 32

The touchscreen implementation is from the touchscreen crate, but significantly modified:
* TouchScreen instance no longer owns the LCD.  That wasn't being used in the crate and was clearly there to make way for a future calibration routine.  This really made it difficult to split the xpt2046 and ili9xxx instances into separate embassy tasks, which really assists in drawing on the screen.

Reliability: Nope.  Things crash after a bit, but this ought to ease your efforts if you want to add a no_std example, upgrade to embedded-hal v1.0.0, or hack in a touchscreen on your existing example.  Good luck!

### CODE REVIEW

**Comment by bobsrac** [comment]
And, here's a quick video of it doing a thing:
https://github.com/user-attachments/assets/808c84c4-da3b-4b9a-b5b4-7fe7064489bf

**Comment by bobsrac** [comment]
I was doing that as part of an HVAC zone controller project where I'm running rust on a cluster of esp32 devices to run damper servos, measure room temperature/humidity/presence, and then run a human interface controller device with data logging and such.  The official CYD is a bit small for that, and I'm not fond of the resistive touch, so I might end up building a gtk4-rs application for a raspberry pi with one of their 7" capacitive screens.  I expect I'll open source the thing at some point here.

**Comment by TheNitek** [comment]
While highly appreciating every contribution, I am reluctant to merge this: This repo currently fully focuses on the CYD (2.8" resistive) and we don't have concept of adding examples/information for other variants for now.

**Comment by bobsrac** [comment]
Yep. Makes total sense and wasn't thinking you would merge it directly. The
code is almost targeted at your official board, but I don't have one of
those. Was mostly an offer to get you .ost of the way to having another
example for your official board.

I did not realize when I purchased an unofficial clone that I was doing so.

Best,
Matt

**Comment by TheNitek** [comment]
If you could move the code into a folder in variants/3248S035C/examples we could merge it for now.

**Comment by bobsrac** [comment]
Moved and added a README.md that tries to cover the caveats noted above.  Iterated a few times to get the README to look reasonable.  Anywho... I'll stop fiddling :)

**Pull request merged**
